### ISSUE TITLE
Switch to Scapy v2.4.0? 

### ISSUE THREAD

**Issue by guedou** [scratchfive/Tethys#6]
I noticed that your are using an outdate Scapy fork diverged, that does not follow evolutions and fixes from https://github.com/secdev/scapy

You should consider switching to scapy in you requirements.txt

**Comment by scratchfive** [comment]
The requirements file is known to be outdated and currently, Scapy isn't being used at all. The requirements will be updated in the next commit and I will consider this suggestion in future releases if the need arises, but until them this issue will be closed.
